### ISSUE TITLE
Suggestions tab not loading after upgrade to v1.2.1

### ISSUE THREAD

**Issue by Anish-Peethambaran** [Geta/404handler#221]
I am facing issues in redirects manager after upgrading to latest version v 1.2.1. Custom redirects suggestions are having some 355470 records but when I click on the suggestions tab it is taking long time and shows blank screen. But no errors are logged. I tried to delete all records from administrator page. It deleted all custom redirects but suggestions are not deleted. It seems deletion is not working for suggestions.

**Comment by oyvindwh** [comment]
We have the same behaviour with v1.2.1. Here is the error from the log.

`Error executing child request for handler 'System.Web.Mvc.HttpHandlerUtil+ServerExecuteHttpHandlerWrapper'. ---> System.Web.HttpCompileException (0x80004005): http://server/EPiServer/BVNetwork.404Handler/Views/NotFoundRedirect/Suggestions.ascx(40): error CS1929: 'HtmlHelper<RedirectIndexViewData>' does not contain a definition for 'Translate' and the best extension method overload 'CultureInfoExtensions.Translate(CultureInfo, LocalizationService)' requires a receiver of type 'CultureInfo'
   at System.Web.Compilation.AssemblyBuilder.Compile()
   at System.Web.Compilation.BuildProvidersCompiler.PerformBuild()
   at System.Web.Compilation.BuildManager.CompileWebFile(VirtualPath virtualPath)
   at System.Web.Compilation.BuildManager.GetVPathBuildResultInternal(VirtualPath virtualPath, Boolean noBuild, Boolean allowCrossApp, Boolean allowBuildInPrecompile, Boolean throwIfNotFound, Boolean ensureIsUpToDate)
   at System.Web.Compilation.BuildManager.GetVPathBuildResultWithNoAssert(HttpContext context, VirtualPath virtualPath, Boolean noBuild, Boolean allowCrossApp, Boolean allowBuildInPrecompile, Boolean throwIfNotFound, Boolean ensureIsUpToDate)
   at System.Web.Compilation.BuildManager.GetVirtualPathObjectFactory(VirtualPath virtualPath, HttpContext context, Boolean allowCrossApp, Boolean throwIfNotFound)
   at System.Web.Compilation.BuildManager.GetCompiledType(VirtualPath virtualPath)
   at System.Web.Mvc.BuildManagerCompiledView.Render(ViewContext viewContext, TextWriter writer)
   at System.Web.Mvc.Html.RenderPartialExtensions.RenderPartial(HtmlHelper htmlHelper, String partialViewName, Object model)
   at ASP.episerver_bvnetwork_404handler_views_notfoundredirect_index_ascx.__Render__control1(HtmlTextWriter __w, Control parameterContainer) in http://server/EPiServer/BVNetwork.404Handler/Views/NotFoundRedirect/Index.ascx:line 5`
